### ISSUE TITLE
Sidebar files heavily indented since latest update

### ISSUE THREAD

**Issue by Theowningone** [netatoo/phoenix-theme#46]
Since the latest update (Jan6th 2015) it appears all of the files in the sidebar are indented much more than prior to the patch, making it much more confusing to understand where they are in the folder structure.

![phoenixthemeindentation](https://cloud.githubusercontent.com/assets/444681/12209353/5179cff2-b620-11e5-8079-396fe6724d35.jpg)

**Comment by ozeebee** [comment]
+1

**Comment by ozeebee** [comment]
Until this bug is fixed, I reverted the last changes simply by overriding the settings as described in https://packagecontrol.io/docs/customizing_packages#Overrides:
1. Create a `Sublime Text 3/Packages/Theme - Phoenix` directory
2. In this directory, override the `Phoenix Dark.sublime-theme` or `Phoenix Light.sublime-theme` (depending on the one you're using)
3. Copy the content of the file from this repository (or from the file of the same name in the package, a zip file actually) into the created one
4. Change the `content-margin` values at line 2171 (under `// FIX FOR DUPLICATE SIDEBAR ICONS`) back to `[0, 0]` instead of `[8, 8]`
5. et voilà, this should be working as before now

**Comment by Theowningone** [comment]
Thanks so much for the workaround, my sanity is restored!

**Comment by ozeebee** [comment]
looks like latest changes have been reverted in the last release so I guess you can close this ticket.

**Comment by Rv-Designs** [comment]
Hi, 


We are planning a  trip to the mountains during the  spring  break,  can you please take  a look at our list of equipment? Here it is <http://practice.proqualityhomeimprovements.com/e4hvxhh>

Warmly, reinierensabine

3070965

**Comment by Rv-Designs** [comment]
Hi! 

I've  got  some new stuff, what do you think about  it? Check it out here <http://compare.wheel2deal.com/e4wsugkt>

Be well, reinierensabine
